version: '2'

services:
  nginx:
    build: ./nginx
    image: nginx-rp
    links:
      - 'app:app'
    ports:
      - '80:80'
    restart: always
  redis:
    image: redis
    restart: always
  app:
    build: ./route-app
    image: app
    command: npm start
    volumes:
      - .:/code
    env_file:
      - ./route-app/.env

