version: '2'

services:
  redis:
    image: redis
    ports:
      - '63790:6379'
  web:
    image: sttraft/route-app
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/code